### 로그인
POST http://localhost:8080/api/authenticate
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### 회원가입
POST http://localhost:8080/api/signup
Content-Type: application/json

{
  "username": "wjdrmsl",
  "password":"password",
  "nickname": "별명입니다"
}

### 내 정보 조회
GET http://localhost:8080/api/user/admin

